baseURL = "https://aparcar.org"
theme = 'hugo-bearblog'

title = "aparcar"
author = "Paul Spooren"
copyright = "Copyright © 2020, Paul Spooren."
languageCode = "en-US"

enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  title = "aparcar"
  hideMadeWithLine = true

[markup]
  [markup.highlight]
    style = "friendly"
